/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.UltFace.Sdk;

public class UltFaceSdkResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UltFaceSdkResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UltFaceSdkResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(UltFaceSdkResult obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ultimateFaceSDKJNI.delete_UltFaceSdkResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UltFaceSdkResult() {
    this(ultimateFaceSDKJNI.new_UltFaceSdkResult__SWIG_0(), true);
  }

  public UltFaceSdkResult(int code, String phrase, String json, long numFaces) {
    this(ultimateFaceSDKJNI.new_UltFaceSdkResult__SWIG_1(code, phrase, json, numFaces), true);
  }

  public UltFaceSdkResult(int code, String phrase, String json) {
    this(ultimateFaceSDKJNI.new_UltFaceSdkResult__SWIG_2(code, phrase, json), true);
  }

  public UltFaceSdkResult(UltFaceSdkResult other) {
    this(ultimateFaceSDKJNI.new_UltFaceSdkResult__SWIG_3(UltFaceSdkResult.getCPtr(other), other), true);
  }

  public int code() {
    return ultimateFaceSDKJNI.UltFaceSdkResult_code(swigCPtr, this);
  }

  public String phrase() {
    return ultimateFaceSDKJNI.UltFaceSdkResult_phrase(swigCPtr, this);
  }

  public String json() {
    return ultimateFaceSDKJNI.UltFaceSdkResult_json(swigCPtr, this);
  }

  public long numFaces() {
    return ultimateFaceSDKJNI.UltFaceSdkResult_numFaces(swigCPtr, this);
  }

  public boolean isOK() {
    return ultimateFaceSDKJNI.UltFaceSdkResult_isOK(swigCPtr, this);
  }

}
