/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.UltFace.Sdk;

public class UltFaceImageInfoCompressed extends UltFaceImageInfo {
  private transient long swigCPtr;

  protected UltFaceImageInfoCompressed(long cPtr, boolean cMemoryOwn) {
    super(ultimateFaceSDKJNI.UltFaceImageInfoCompressed_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UltFaceImageInfoCompressed obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(UltFaceImageInfoCompressed obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ultimateFaceSDKJNI.delete_UltFaceImageInfoCompressed(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public UltFaceImageInfoCompressed(java.nio.ByteBuffer data_ptr, long data_size) {
    this(ultimateFaceSDKJNI.new_UltFaceImageInfoCompressed(data_ptr, data_size), true);
  }

}
