/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.UltFace.Sdk;

public class UltFaceSdkParallelDeliveryCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UltFaceSdkParallelDeliveryCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UltFaceSdkParallelDeliveryCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(UltFaceSdkParallelDeliveryCallback obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ultimateFaceSDKJNI.delete_UltFaceSdkParallelDeliveryCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void onNewResult(UltFaceSdkResult newResult) {
    ultimateFaceSDKJNI.UltFaceSdkParallelDeliveryCallback_onNewResult(swigCPtr, this, UltFaceSdkResult.getCPtr(newResult), newResult);
  }

}
