/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.UltFace.Sdk;

public class UltFaceSdkEngine {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UltFaceSdkEngine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UltFaceSdkEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(UltFaceSdkEngine obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ultimateFaceSDKJNI.delete_UltFaceSdkEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static UltFaceSdkResult init(java.lang.Object assetManager, String jsonConfig, UltFaceSdkParallelDeliveryCallback parallelDeliveryCallback) {
    return new UltFaceSdkResult(ultimateFaceSDKJNI.UltFaceSdkEngine_init__SWIG_0(assetManager, jsonConfig, UltFaceSdkParallelDeliveryCallback.getCPtr(parallelDeliveryCallback), parallelDeliveryCallback), true);
  }

  public static UltFaceSdkResult init(java.lang.Object assetManager, String jsonConfig) {
    return new UltFaceSdkResult(ultimateFaceSDKJNI.UltFaceSdkEngine_init__SWIG_1(assetManager, jsonConfig), true);
  }

  public static UltFaceSdkResult deInit() {
    return new UltFaceSdkResult(ultimateFaceSDKJNI.UltFaceSdkEngine_deInit(), true);
  }

  public static UltFaceSdkResult process_liveness(UltFaceImageInfo image) {
    return new UltFaceSdkResult(ultimateFaceSDKJNI.UltFaceSdkEngine_process_liveness(UltFaceImageInfo.getCPtr(image), image), true);
  }

  public static UltFaceSdkResult process_inject(UltFaceImageInfo stereo_main, UltFaceImageInfo stereo_aux, String aggressive_mode) {
    return new UltFaceSdkResult(ultimateFaceSDKJNI.UltFaceSdkEngine_process_inject__SWIG_0(UltFaceImageInfo.getCPtr(stereo_main), stereo_main, UltFaceImageInfo.getCPtr(stereo_aux), stereo_aux, aggressive_mode), true);
  }

  public static UltFaceSdkResult process_inject(UltFaceImageInfo stereo_main, UltFaceImageInfo stereo_aux) {
    return new UltFaceSdkResult(ultimateFaceSDKJNI.UltFaceSdkEngine_process_inject__SWIG_1(UltFaceImageInfo.getCPtr(stereo_main), stereo_main, UltFaceImageInfo.getCPtr(stereo_aux), stereo_aux), true);
  }

  public static UltFaceSdkResult process_recognition(UltFaceImageInfo image) {
    return new UltFaceSdkResult(ultimateFaceSDKJNI.UltFaceSdkEngine_process_recognition(UltFaceImageInfo.getCPtr(image), image), true);
  }

  public static int exifOrientation(java.nio.ByteBuffer jpegMetaDataPtr, long jpegMetaDataSize) {
    return ultimateFaceSDKJNI.UltFaceSdkEngine_exifOrientation(jpegMetaDataPtr, jpegMetaDataSize);
  }

  public static UltFaceSdkResult requestRuntimeLicenseKey(boolean rawInsteadOfJSON) {
    return new UltFaceSdkResult(ultimateFaceSDKJNI.UltFaceSdkEngine_requestRuntimeLicenseKey__SWIG_0(rawInsteadOfJSON), true);
  }

  public static UltFaceSdkResult requestRuntimeLicenseKey() {
    return new UltFaceSdkResult(ultimateFaceSDKJNI.UltFaceSdkEngine_requestRuntimeLicenseKey__SWIG_1(), true);
  }

}
