/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.UltFace.Sdk;

public class ultimateFaceSDKJNI {

  static {
    System.loadLibrary("FaceLivenessDetectionSDK");
  }

  public final static native void delete_UltFaceImageInfo(long jarg1);
  public final static native long new_UltFaceImageInfoCompressed(java.nio.ByteBuffer jarg1, long jarg2);
  public final static native void delete_UltFaceImageInfoCompressed(long jarg1);
  public final static native void delete_UltFaceImageInfoUncompressed(long jarg1);
  public final static native long new_UltFaceImageInfoRgbFamily__SWIG_0(int jarg1, java.nio.ByteBuffer jarg2, long jarg3, long jarg4, long jarg5, int jarg6);
  public final static native long new_UltFaceImageInfoRgbFamily__SWIG_1(int jarg1, java.nio.ByteBuffer jarg2, long jarg3, long jarg4, long jarg5);
  public final static native long new_UltFaceImageInfoRgbFamily__SWIG_2(int jarg1, java.nio.ByteBuffer jarg2, long jarg3, long jarg4);
  public final static native void delete_UltFaceImageInfoRgbFamily(long jarg1);
  public final static native long new_UltFaceImageInfoYuvFamily__SWIG_0(int jarg1, java.nio.ByteBuffer jarg2, java.nio.ByteBuffer jarg3, java.nio.ByteBuffer jarg4, long jarg5, long jarg6, long jarg7, long jarg8, long jarg9, long jarg10, int jarg11);
  public final static native long new_UltFaceImageInfoYuvFamily__SWIG_1(int jarg1, java.nio.ByteBuffer jarg2, java.nio.ByteBuffer jarg3, java.nio.ByteBuffer jarg4, long jarg5, long jarg6, long jarg7, long jarg8, long jarg9, long jarg10);
  public final static native long new_UltFaceImageInfoYuvFamily__SWIG_2(int jarg1, java.nio.ByteBuffer jarg2, java.nio.ByteBuffer jarg3, java.nio.ByteBuffer jarg4, long jarg5, long jarg6, long jarg7, long jarg8, long jarg9);
  public final static native void delete_UltFaceImageInfoYuvFamily(long jarg1);
  public final static native long new_UltFaceSdkResult__SWIG_0();
  public final static native long new_UltFaceSdkResult__SWIG_1(int jarg1, String jarg2, String jarg3, long jarg4);
  public final static native long new_UltFaceSdkResult__SWIG_2(int jarg1, String jarg2, String jarg3);
  public final static native long new_UltFaceSdkResult__SWIG_3(long jarg1, UltFaceSdkResult jarg1_);
  public final static native void delete_UltFaceSdkResult(long jarg1);
  public final static native int UltFaceSdkResult_code(long jarg1, UltFaceSdkResult jarg1_);
  public final static native String UltFaceSdkResult_phrase(long jarg1, UltFaceSdkResult jarg1_);
  public final static native String UltFaceSdkResult_json(long jarg1, UltFaceSdkResult jarg1_);
  public final static native long UltFaceSdkResult_numFaces(long jarg1, UltFaceSdkResult jarg1_);
  public final static native boolean UltFaceSdkResult_isOK(long jarg1, UltFaceSdkResult jarg1_);
  public final static native void delete_UltFaceSdkParallelDeliveryCallback(long jarg1);
  public final static native void UltFaceSdkParallelDeliveryCallback_onNewResult(long jarg1, UltFaceSdkParallelDeliveryCallback jarg1_, long jarg2, UltFaceSdkResult jarg2_);
  public final static native long UltFaceSdkEngine_init__SWIG_0(java.lang.Object jarg1, String jarg2, long jarg3, UltFaceSdkParallelDeliveryCallback jarg3_);
  public final static native long UltFaceSdkEngine_init__SWIG_1(java.lang.Object jarg1, String jarg2);
  public final static native long UltFaceSdkEngine_deInit();
  public final static native long UltFaceSdkEngine_process_liveness(long jarg1, UltFaceImageInfo jarg1_);
  public final static native long UltFaceSdkEngine_process_inject__SWIG_0(long jarg1, UltFaceImageInfo jarg1_, long jarg2, UltFaceImageInfo jarg2_, String jarg3);
  public final static native long UltFaceSdkEngine_process_inject__SWIG_1(long jarg1, UltFaceImageInfo jarg1_, long jarg2, UltFaceImageInfo jarg2_);
  public final static native long UltFaceSdkEngine_process_recognition(long jarg1, UltFaceImageInfo jarg1_);
  public final static native int UltFaceSdkEngine_exifOrientation(java.nio.ByteBuffer jarg1, long jarg2);
  public final static native long UltFaceSdkEngine_requestRuntimeLicenseKey__SWIG_0(boolean jarg1);
  public final static native long UltFaceSdkEngine_requestRuntimeLicenseKey__SWIG_1();
  public final static native void delete_UltFaceSdkEngine(long jarg1);
  public final static native long UltFaceImageInfoCompressed_SWIGUpcast(long jarg1);
  public final static native long UltFaceImageInfoUncompressed_SWIGUpcast(long jarg1);
  public final static native long UltFaceImageInfoRgbFamily_SWIGUpcast(long jarg1);
  public final static native long UltFaceImageInfoYuvFamily_SWIGUpcast(long jarg1);
}
