/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.UltFace.Sdk;

public enum ULTFACE_SDK_IMAGE_TYPE {
  ULTFACE_SDK_IMAGE_TYPE_RGB24,
  ULTFACE_SDK_IMAGE_TYPE_RGBA32,
  ULTFACE_SDK_IMAGE_TYPE_BGRA32,
  ULTFACE_SDK_IMAGE_TYPE_BGR24,
  ULTFACE_SDK_IMAGE_TYPE_NV12,
  ULTFACE_SDK_IMAGE_TYPE_NV21,
  ULTFACE_SDK_IMAGE_TYPE_YUV420P,
  ULTFACE_SDK_IMAGE_TYPE_YVU420P,
  ULTFACE_SDK_IMAGE_TYPE_YUV422P,
  ULTFACE_SDK_IMAGE_TYPE_YUV444P,
  ULTFACE_SDK_IMAGE_TYPE_Y;

  public final int swigValue() {
    return swigValue;
  }

  public static ULTFACE_SDK_IMAGE_TYPE swigToEnum(int swigValue) {
    ULTFACE_SDK_IMAGE_TYPE[] swigValues = ULTFACE_SDK_IMAGE_TYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ULTFACE_SDK_IMAGE_TYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ULTFACE_SDK_IMAGE_TYPE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ULTFACE_SDK_IMAGE_TYPE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ULTFACE_SDK_IMAGE_TYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ULTFACE_SDK_IMAGE_TYPE(ULTFACE_SDK_IMAGE_TYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

