/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.UltFace.Sdk;

public class UltFaceImageInfoYuvFamily extends UltFaceImageInfoUncompressed {
  private transient long swigCPtr;

  protected UltFaceImageInfoYuvFamily(long cPtr, boolean cMemoryOwn) {
    super(ultimateFaceSDKJNI.UltFaceImageInfoYuvFamily_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UltFaceImageInfoYuvFamily obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(UltFaceImageInfoYuvFamily obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ultimateFaceSDKJNI.delete_UltFaceImageInfoYuvFamily(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public UltFaceImageInfoYuvFamily(ULTFACE_SDK_IMAGE_TYPE chroma, java.nio.ByteBuffer yPtr, java.nio.ByteBuffer uPtr, java.nio.ByteBuffer vPtr, long widthInSamples, long heightInSamples, long yStrideInBytes, long uStrideInBytes, long vStrideInBytes, long uvPixelStrideInBytes, int exifOrientation) {
    this(ultimateFaceSDKJNI.new_UltFaceImageInfoYuvFamily__SWIG_0(chroma.swigValue(), yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes, exifOrientation), true);
  }

  public UltFaceImageInfoYuvFamily(ULTFACE_SDK_IMAGE_TYPE chroma, java.nio.ByteBuffer yPtr, java.nio.ByteBuffer uPtr, java.nio.ByteBuffer vPtr, long widthInSamples, long heightInSamples, long yStrideInBytes, long uStrideInBytes, long vStrideInBytes, long uvPixelStrideInBytes) {
    this(ultimateFaceSDKJNI.new_UltFaceImageInfoYuvFamily__SWIG_1(chroma.swigValue(), yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes), true);
  }

  public UltFaceImageInfoYuvFamily(ULTFACE_SDK_IMAGE_TYPE chroma, java.nio.ByteBuffer yPtr, java.nio.ByteBuffer uPtr, java.nio.ByteBuffer vPtr, long widthInSamples, long heightInSamples, long yStrideInBytes, long uStrideInBytes, long vStrideInBytes) {
    this(ultimateFaceSDKJNI.new_UltFaceImageInfoYuvFamily__SWIG_2(chroma.swigValue(), yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes), true);
  }

}
