/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.UltFace.Sdk;

public class UltFaceImageInfoRgbFamily extends UltFaceImageInfoUncompressed {
  private transient long swigCPtr;

  protected UltFaceImageInfoRgbFamily(long cPtr, boolean cMemoryOwn) {
    super(ultimateFaceSDKJNI.UltFaceImageInfoRgbFamily_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UltFaceImageInfoRgbFamily obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(UltFaceImageInfoRgbFamily obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ultimateFaceSDKJNI.delete_UltFaceImageInfoRgbFamily(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public UltFaceImageInfoRgbFamily(ULTFACE_SDK_IMAGE_TYPE chroma, java.nio.ByteBuffer rgbPtr, long widthInSamples, long heightInSamples, long strideInSamples, int exifOrientation) {
    this(ultimateFaceSDKJNI.new_UltFaceImageInfoRgbFamily__SWIG_0(chroma.swigValue(), rgbPtr, widthInSamples, heightInSamples, strideInSamples, exifOrientation), true);
  }

  public UltFaceImageInfoRgbFamily(ULTFACE_SDK_IMAGE_TYPE chroma, java.nio.ByteBuffer rgbPtr, long widthInSamples, long heightInSamples, long strideInSamples) {
    this(ultimateFaceSDKJNI.new_UltFaceImageInfoRgbFamily__SWIG_1(chroma.swigValue(), rgbPtr, widthInSamples, heightInSamples, strideInSamples), true);
  }

  public UltFaceImageInfoRgbFamily(ULTFACE_SDK_IMAGE_TYPE chroma, java.nio.ByteBuffer rgbPtr, long widthInSamples, long heightInSamples) {
    this(ultimateFaceSDKJNI.new_UltFaceImageInfoRgbFamily__SWIG_2(chroma.swigValue(), rgbPtr, widthInSamples, heightInSamples), true);
  }

}
