# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _ultimateFaceSDK
else:
    import _ultimateFaceSDK

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

ULTFACE_SDK_VERSION_MAJOR = _ultimateFaceSDK.ULTFACE_SDK_VERSION_MAJOR
ULTFACE_SDK_VERSION_MINOR = _ultimateFaceSDK.ULTFACE_SDK_VERSION_MINOR
ULTFACE_SDK_VERSION_MICRO = _ultimateFaceSDK.ULTFACE_SDK_VERSION_MICRO
ULTFACE_SDK_IMAGE_TYPE_RGB24 = _ultimateFaceSDK.ULTFACE_SDK_IMAGE_TYPE_RGB24
ULTFACE_SDK_IMAGE_TYPE_RGBA32 = _ultimateFaceSDK.ULTFACE_SDK_IMAGE_TYPE_RGBA32
ULTFACE_SDK_IMAGE_TYPE_BGRA32 = _ultimateFaceSDK.ULTFACE_SDK_IMAGE_TYPE_BGRA32
ULTFACE_SDK_IMAGE_TYPE_BGR24 = _ultimateFaceSDK.ULTFACE_SDK_IMAGE_TYPE_BGR24
ULTFACE_SDK_IMAGE_TYPE_NV12 = _ultimateFaceSDK.ULTFACE_SDK_IMAGE_TYPE_NV12
ULTFACE_SDK_IMAGE_TYPE_NV21 = _ultimateFaceSDK.ULTFACE_SDK_IMAGE_TYPE_NV21
ULTFACE_SDK_IMAGE_TYPE_YUV420P = _ultimateFaceSDK.ULTFACE_SDK_IMAGE_TYPE_YUV420P
ULTFACE_SDK_IMAGE_TYPE_YVU420P = _ultimateFaceSDK.ULTFACE_SDK_IMAGE_TYPE_YVU420P
ULTFACE_SDK_IMAGE_TYPE_YUV422P = _ultimateFaceSDK.ULTFACE_SDK_IMAGE_TYPE_YUV422P
ULTFACE_SDK_IMAGE_TYPE_YUV444P = _ultimateFaceSDK.ULTFACE_SDK_IMAGE_TYPE_YUV444P
ULTFACE_SDK_IMAGE_TYPE_Y = _ultimateFaceSDK.ULTFACE_SDK_IMAGE_TYPE_Y
class UltFaceImageInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    Compressed = _ultimateFaceSDK.UltFaceImageInfo_Compressed
    Uncompressed = _ultimateFaceSDK.UltFaceImageInfo_Uncompressed
    __swig_destroy__ = _ultimateFaceSDK.delete_UltFaceImageInfo

# Register UltFaceImageInfo in _ultimateFaceSDK:
_ultimateFaceSDK.UltFaceImageInfo_swigregister(UltFaceImageInfo)
class UltFaceImageInfoCompressed(UltFaceImageInfo):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, data_ptr, data_size):
        _ultimateFaceSDK.UltFaceImageInfoCompressed_swiginit(self, _ultimateFaceSDK.new_UltFaceImageInfoCompressed(data_ptr, data_size))
    __swig_destroy__ = _ultimateFaceSDK.delete_UltFaceImageInfoCompressed

# Register UltFaceImageInfoCompressed in _ultimateFaceSDK:
_ultimateFaceSDK.UltFaceImageInfoCompressed_swigregister(UltFaceImageInfoCompressed)
class UltFaceImageInfoUncompressed(UltFaceImageInfo):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _ultimateFaceSDK.delete_UltFaceImageInfoUncompressed

# Register UltFaceImageInfoUncompressed in _ultimateFaceSDK:
_ultimateFaceSDK.UltFaceImageInfoUncompressed_swigregister(UltFaceImageInfoUncompressed)
class UltFaceImageInfoRgbFamily(UltFaceImageInfoUncompressed):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, chroma, rgbPtr, widthInSamples, heightInSamples, strideInSamples=0, exifOrientation=1):
        _ultimateFaceSDK.UltFaceImageInfoRgbFamily_swiginit(self, _ultimateFaceSDK.new_UltFaceImageInfoRgbFamily(chroma, rgbPtr, widthInSamples, heightInSamples, strideInSamples, exifOrientation))
    __swig_destroy__ = _ultimateFaceSDK.delete_UltFaceImageInfoRgbFamily

# Register UltFaceImageInfoRgbFamily in _ultimateFaceSDK:
_ultimateFaceSDK.UltFaceImageInfoRgbFamily_swigregister(UltFaceImageInfoRgbFamily)
class UltFaceImageInfoYuvFamily(UltFaceImageInfoUncompressed):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, chroma, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes=0, exifOrientation=1):
        _ultimateFaceSDK.UltFaceImageInfoYuvFamily_swiginit(self, _ultimateFaceSDK.new_UltFaceImageInfoYuvFamily(chroma, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes, exifOrientation))
    __swig_destroy__ = _ultimateFaceSDK.delete_UltFaceImageInfoYuvFamily

# Register UltFaceImageInfoYuvFamily in _ultimateFaceSDK:
_ultimateFaceSDK.UltFaceImageInfoYuvFamily_swigregister(UltFaceImageInfoYuvFamily)
class UltFaceSdkResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _ultimateFaceSDK.UltFaceSdkResult_swiginit(self, _ultimateFaceSDK.new_UltFaceSdkResult(*args))
    __swig_destroy__ = _ultimateFaceSDK.delete_UltFaceSdkResult

    def code(self):
        return _ultimateFaceSDK.UltFaceSdkResult_code(self)

    def phrase(self):
        return _ultimateFaceSDK.UltFaceSdkResult_phrase(self)

    def json(self):
        return _ultimateFaceSDK.UltFaceSdkResult_json(self)

    def numFaces(self):
        return _ultimateFaceSDK.UltFaceSdkResult_numFaces(self)

    def isOK(self):
        return _ultimateFaceSDK.UltFaceSdkResult_isOK(self)

# Register UltFaceSdkResult in _ultimateFaceSDK:
_ultimateFaceSDK.UltFaceSdkResult_swigregister(UltFaceSdkResult)
class UltFaceSdkParallelDeliveryCallback(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ultimateFaceSDK.delete_UltFaceSdkParallelDeliveryCallback

    def onNewResult(self, newResult):
        return _ultimateFaceSDK.UltFaceSdkParallelDeliveryCallback_onNewResult(self, newResult)

# Register UltFaceSdkParallelDeliveryCallback in _ultimateFaceSDK:
_ultimateFaceSDK.UltFaceSdkParallelDeliveryCallback_swigregister(UltFaceSdkParallelDeliveryCallback)
class UltFaceSdkEngine(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def init(jsonConfig, parallelDeliveryCallback=None):
        return _ultimateFaceSDK.UltFaceSdkEngine_init(jsonConfig, parallelDeliveryCallback)

    @staticmethod
    def deInit():
        return _ultimateFaceSDK.UltFaceSdkEngine_deInit()

    @staticmethod
    def process_liveness(image):
        return _ultimateFaceSDK.UltFaceSdkEngine_process_liveness(image)

    @staticmethod
    def process_inject(*args):
        return _ultimateFaceSDK.UltFaceSdkEngine_process_inject(*args)

    @staticmethod
    def process_recognition(image):
        return _ultimateFaceSDK.UltFaceSdkEngine_process_recognition(image)

    @staticmethod
    def exifOrientation(jpegMetaDataPtr, jpegMetaDataSize):
        return _ultimateFaceSDK.UltFaceSdkEngine_exifOrientation(jpegMetaDataPtr, jpegMetaDataSize)

    @staticmethod
    def requestRuntimeLicenseKey(rawInsteadOfJSON=False):
        return _ultimateFaceSDK.UltFaceSdkEngine_requestRuntimeLicenseKey(rawInsteadOfJSON)
    __swig_destroy__ = _ultimateFaceSDK.delete_UltFaceSdkEngine

# Register UltFaceSdkEngine in _ultimateFaceSDK:
_ultimateFaceSDK.UltFaceSdkEngine_swigregister(UltFaceSdkEngine)

