//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.doubango.UltFace.Sdk {

public class UltFaceImageInfoYuvFamily : UltFaceImageInfoUncompressed {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal UltFaceImageInfoYuvFamily(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ultimateFaceSDKPINVOKE.UltFaceImageInfoYuvFamily_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UltFaceImageInfoYuvFamily obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(UltFaceImageInfoYuvFamily obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ultimateFaceSDKPINVOKE.delete_UltFaceImageInfoYuvFamily(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public UltFaceImageInfoYuvFamily(ULTFACE_SDK_IMAGE_TYPE chroma, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes, uint uvPixelStrideInBytes, int exifOrientation) : this(ultimateFaceSDKPINVOKE.new_UltFaceImageInfoYuvFamily__SWIG_0((int)chroma, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes, exifOrientation), true) {
  }

  public UltFaceImageInfoYuvFamily(ULTFACE_SDK_IMAGE_TYPE chroma, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes, uint uvPixelStrideInBytes) : this(ultimateFaceSDKPINVOKE.new_UltFaceImageInfoYuvFamily__SWIG_1((int)chroma, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes), true) {
  }

  public UltFaceImageInfoYuvFamily(ULTFACE_SDK_IMAGE_TYPE chroma, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes) : this(ultimateFaceSDKPINVOKE.new_UltFaceImageInfoYuvFamily__SWIG_2((int)chroma, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes), true) {
  }

}

}
