//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.doubango.UltFace.Sdk {

public enum ULTFACE_SDK_IMAGE_TYPE {
  ULTFACE_SDK_IMAGE_TYPE_RGB24,
  ULTFACE_SDK_IMAGE_TYPE_RGBA32,
  ULTFACE_SDK_IMAGE_TYPE_BGRA32,
  ULTFACE_SDK_IMAGE_TYPE_BGR24,
  ULTFACE_SDK_IMAGE_TYPE_NV12,
  ULTFACE_SDK_IMAGE_TYPE_NV21,
  ULTFACE_SDK_IMAGE_TYPE_YUV420P,
  ULTFACE_SDK_IMAGE_TYPE_YVU420P,
  ULTFACE_SDK_IMAGE_TYPE_YUV422P,
  ULTFACE_SDK_IMAGE_TYPE_YUV444P,
  ULTFACE_SDK_IMAGE_TYPE_Y
}

}
