//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.doubango.UltFace.Sdk {

public class UltFaceSdkResult : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UltFaceSdkResult(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UltFaceSdkResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(UltFaceSdkResult obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~UltFaceSdkResult() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ultimateFaceSDKPINVOKE.delete_UltFaceSdkResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public UltFaceSdkResult() : this(ultimateFaceSDKPINVOKE.new_UltFaceSdkResult__SWIG_0(), true) {
  }

  public UltFaceSdkResult(int code, string phrase, string json, uint numFaces) : this(ultimateFaceSDKPINVOKE.new_UltFaceSdkResult__SWIG_1(code, phrase, json, numFaces), true) {
  }

  public UltFaceSdkResult(int code, string phrase, string json) : this(ultimateFaceSDKPINVOKE.new_UltFaceSdkResult__SWIG_2(code, phrase, json), true) {
  }

  public UltFaceSdkResult(UltFaceSdkResult other) : this(ultimateFaceSDKPINVOKE.new_UltFaceSdkResult__SWIG_3(UltFaceSdkResult.getCPtr(other)), true) {
    if (ultimateFaceSDKPINVOKE.SWIGPendingException.Pending) throw ultimateFaceSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public int code() {
    int ret = ultimateFaceSDKPINVOKE.UltFaceSdkResult_code(swigCPtr);
    return ret;
  }

  public string phrase() {
    string ret = ultimateFaceSDKPINVOKE.UltFaceSdkResult_phrase(swigCPtr);
    return ret;
  }

  public string json() {
    string ret = ultimateFaceSDKPINVOKE.UltFaceSdkResult_json(swigCPtr);
    return ret;
  }

  public uint numFaces() {
    uint ret = ultimateFaceSDKPINVOKE.UltFaceSdkResult_numFaces(swigCPtr);
    return ret;
  }

  public bool isOK() {
    bool ret = ultimateFaceSDKPINVOKE.UltFaceSdkResult_isOK(swigCPtr);
    return ret;
  }

}

}
