//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.doubango.UltFace.Sdk {

public class UltFaceImageInfoRgbFamily : UltFaceImageInfoUncompressed {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal UltFaceImageInfoRgbFamily(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ultimateFaceSDKPINVOKE.UltFaceImageInfoRgbFamily_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UltFaceImageInfoRgbFamily obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(UltFaceImageInfoRgbFamily obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ultimateFaceSDKPINVOKE.delete_UltFaceImageInfoRgbFamily(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public UltFaceImageInfoRgbFamily(ULTFACE_SDK_IMAGE_TYPE chroma, IntPtr rgbPtr, uint widthInSamples, uint heightInSamples, uint strideInSamples, int exifOrientation) : this(ultimateFaceSDKPINVOKE.new_UltFaceImageInfoRgbFamily__SWIG_0((int)chroma, rgbPtr, widthInSamples, heightInSamples, strideInSamples, exifOrientation), true) {
  }

  public UltFaceImageInfoRgbFamily(ULTFACE_SDK_IMAGE_TYPE chroma, IntPtr rgbPtr, uint widthInSamples, uint heightInSamples, uint strideInSamples) : this(ultimateFaceSDKPINVOKE.new_UltFaceImageInfoRgbFamily__SWIG_1((int)chroma, rgbPtr, widthInSamples, heightInSamples, strideInSamples), true) {
  }

  public UltFaceImageInfoRgbFamily(ULTFACE_SDK_IMAGE_TYPE chroma, IntPtr rgbPtr, uint widthInSamples, uint heightInSamples) : this(ultimateFaceSDKPINVOKE.new_UltFaceImageInfoRgbFamily__SWIG_2((int)chroma, rgbPtr, widthInSamples, heightInSamples), true) {
  }

}

}
