//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.doubango.UltFace.Sdk {

public class UltFaceSdkEngine : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UltFaceSdkEngine(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UltFaceSdkEngine obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(UltFaceSdkEngine obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~UltFaceSdkEngine() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ultimateFaceSDKPINVOKE.delete_UltFaceSdkEngine(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static UltFaceSdkResult init(string jsonConfig, UltFaceSdkParallelDeliveryCallback parallelDeliveryCallback) {
    UltFaceSdkResult ret = new UltFaceSdkResult(ultimateFaceSDKPINVOKE.UltFaceSdkEngine_init__SWIG_0(jsonConfig, UltFaceSdkParallelDeliveryCallback.getCPtr(parallelDeliveryCallback)), true);
    return ret;
  }

  public static UltFaceSdkResult init(string jsonConfig) {
    UltFaceSdkResult ret = new UltFaceSdkResult(ultimateFaceSDKPINVOKE.UltFaceSdkEngine_init__SWIG_1(jsonConfig), true);
    return ret;
  }

  public static UltFaceSdkResult deInit() {
    UltFaceSdkResult ret = new UltFaceSdkResult(ultimateFaceSDKPINVOKE.UltFaceSdkEngine_deInit(), true);
    return ret;
  }

  public static UltFaceSdkResult process_liveness(UltFaceImageInfo image) {
    UltFaceSdkResult ret = new UltFaceSdkResult(ultimateFaceSDKPINVOKE.UltFaceSdkEngine_process_liveness(UltFaceImageInfo.getCPtr(image)), true);
    return ret;
  }

  public static UltFaceSdkResult process_inject(UltFaceImageInfo stereo_main, UltFaceImageInfo stereo_aux, string aggressive_mode) {
    UltFaceSdkResult ret = new UltFaceSdkResult(ultimateFaceSDKPINVOKE.UltFaceSdkEngine_process_inject__SWIG_0(UltFaceImageInfo.getCPtr(stereo_main), UltFaceImageInfo.getCPtr(stereo_aux), aggressive_mode), true);
    return ret;
  }

  public static UltFaceSdkResult process_inject(UltFaceImageInfo stereo_main, UltFaceImageInfo stereo_aux) {
    UltFaceSdkResult ret = new UltFaceSdkResult(ultimateFaceSDKPINVOKE.UltFaceSdkEngine_process_inject__SWIG_1(UltFaceImageInfo.getCPtr(stereo_main), UltFaceImageInfo.getCPtr(stereo_aux)), true);
    return ret;
  }

  public static UltFaceSdkResult process_recognition(UltFaceImageInfo image) {
    UltFaceSdkResult ret = new UltFaceSdkResult(ultimateFaceSDKPINVOKE.UltFaceSdkEngine_process_recognition(UltFaceImageInfo.getCPtr(image)), true);
    return ret;
  }

  public static int exifOrientation(IntPtr jpegMetaDataPtr, uint jpegMetaDataSize) {
    int ret = ultimateFaceSDKPINVOKE.UltFaceSdkEngine_exifOrientation(jpegMetaDataPtr, jpegMetaDataSize);
    return ret;
  }

  public static UltFaceSdkResult requestRuntimeLicenseKey(bool rawInsteadOfJSON) {
    UltFaceSdkResult ret = new UltFaceSdkResult(ultimateFaceSDKPINVOKE.UltFaceSdkEngine_requestRuntimeLicenseKey__SWIG_0(rawInsteadOfJSON), true);
    return ret;
  }

  public static UltFaceSdkResult requestRuntimeLicenseKey() {
    UltFaceSdkResult ret = new UltFaceSdkResult(ultimateFaceSDKPINVOKE.UltFaceSdkEngine_requestRuntimeLicenseKey__SWIG_1(), true);
    return ret;
  }

}

}
