/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040400
#define SWIGCSHARP
#define SWIG_DIRECTORS

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NOEXCEPT noexcept
#else
# define SWIG_NOEXCEPT throw()
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_ultimateFaceSDK(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_ultimateFaceSDK(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_ultimateFaceSDK(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } } while (0)

/* -----------------------------------------------------------------------------
 * director_common.swg
 *
 * This file contains support for director classes which is common between
 * languages.
 * ----------------------------------------------------------------------------- */

/*
  Use -DSWIG_DIRECTOR_STATIC if you prefer to avoid the use of the
  'Swig' namespace. This could be useful for multi-modules projects.
*/
#ifdef SWIG_DIRECTOR_STATIC
/* Force anonymous (static) namespace */
#define Swig
#endif
/* -----------------------------------------------------------------------------
 * director.swg
 *
 * This file contains support for director classes so that C# proxy
 * methods can be called from C++.
 * ----------------------------------------------------------------------------- */

#if defined(DEBUG_DIRECTOR_OWNED)
#include <iostream>
#endif
#include <string>
#include <exception>

namespace Swig {
  /* Director base class - not currently used in C# directors */
  class Director {
  };

  /* Base class for director exceptions */
  class DirectorException : public std::exception {
  protected:
    std::string swig_msg;

  public:
    DirectorException(const char *msg) : swig_msg(msg) {
    }

    DirectorException(const std::string &msg) : swig_msg(msg) {
    }

    virtual ~DirectorException() SWIG_NOEXCEPT {
    }

    const char *what() const SWIG_NOEXCEPT {
      return swig_msg.c_str();
    }
  };

  /* Pure virtual method exception */
  class DirectorPureVirtualException : public DirectorException {
  public:
    DirectorPureVirtualException(const char *msg) : DirectorException(std::string("Attempt to invoke pure virtual method ") + msg) {
    }

    static void raise(const char *msg) {
      throw DirectorPureVirtualException(msg);
    }
  };
}


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#include <stdint.h>		// Use the C99 official header


#include <string>


#include "ULTFACE-SDK-API-PUBLIC.h"



/* ---------------------------------------------------
 * C++ director class methods
 * --------------------------------------------------- */

#include "ULTFACE-SDK-API-PUBLIC-SWIG_cscharp.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT int SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_ULTFACE_SDK_VERSION_MAJOR_get___() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_ULTFACE_SDK_VERSION_MINOR_get___() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_ULTFACE_SDK_VERSION_MICRO_get___() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_delete_UltFaceImageInfo___(void * jarg1) {
  UltFace::UltFaceImageInfo *arg1 = 0 ;
  
  arg1 = (UltFace::UltFaceImageInfo *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_new_UltFaceImageInfoCompressed___(void * jarg1, unsigned int jarg2) {
  void * jresult ;
  void *arg1 = 0 ;
  size_t *arg2 = 0 ;
  size_t temp2 ;
  UltFace::UltFaceImageInfoCompressed *result = 0 ;
  
  arg1 = jarg1; 
  temp2 = (size_t)jarg2; 
  arg2 = &temp2; 
  result = (UltFace::UltFaceImageInfoCompressed *)new UltFace::UltFaceImageInfoCompressed((void const *)arg1,(size_t const &)*arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_delete_UltFaceImageInfoCompressed___(void * jarg1) {
  UltFace::UltFaceImageInfoCompressed *arg1 = 0 ;
  
  arg1 = (UltFace::UltFaceImageInfoCompressed *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_delete_UltFaceImageInfoUncompressed___(void * jarg1) {
  UltFace::UltFaceImageInfoUncompressed *arg1 = 0 ;
  
  arg1 = (UltFace::UltFaceImageInfoUncompressed *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_new_UltFaceImageInfoRgbFamily__SWIG_0___(int jarg1, void * jarg2, unsigned int jarg3, unsigned int jarg4, unsigned int jarg5, int jarg6) {
  void * jresult ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE *arg1 = 0 ;
  void *arg2 = 0 ;
  size_t *arg3 = 0 ;
  size_t *arg4 = 0 ;
  size_t *arg5 = 0 ;
  int *arg6 = 0 ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE temp1 ;
  size_t temp3 ;
  size_t temp4 ;
  size_t temp5 ;
  int temp6 ;
  UltFace::UltFaceImageInfoRgbFamily *result = 0 ;
  
  temp1 = (UltFace::ULTFACE_SDK_IMAGE_TYPE)jarg1; 
  arg1 = &temp1; 
  arg2 = jarg2; 
  temp3 = (size_t)jarg3; 
  arg3 = &temp3; 
  temp4 = (size_t)jarg4; 
  arg4 = &temp4; 
  temp5 = (size_t)jarg5; 
  arg5 = &temp5; 
  temp6 = (int)jarg6; 
  arg6 = &temp6; 
  result = (UltFace::UltFaceImageInfoRgbFamily *)new UltFace::UltFaceImageInfoRgbFamily((UltFace::ULTFACE_SDK_IMAGE_TYPE const &)*arg1,(void const *)arg2,(size_t const &)*arg3,(size_t const &)*arg4,(size_t const &)*arg5,(int const &)*arg6);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_new_UltFaceImageInfoRgbFamily__SWIG_1___(int jarg1, void * jarg2, unsigned int jarg3, unsigned int jarg4, unsigned int jarg5) {
  void * jresult ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE *arg1 = 0 ;
  void *arg2 = 0 ;
  size_t *arg3 = 0 ;
  size_t *arg4 = 0 ;
  size_t *arg5 = 0 ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE temp1 ;
  size_t temp3 ;
  size_t temp4 ;
  size_t temp5 ;
  UltFace::UltFaceImageInfoRgbFamily *result = 0 ;
  
  temp1 = (UltFace::ULTFACE_SDK_IMAGE_TYPE)jarg1; 
  arg1 = &temp1; 
  arg2 = jarg2; 
  temp3 = (size_t)jarg3; 
  arg3 = &temp3; 
  temp4 = (size_t)jarg4; 
  arg4 = &temp4; 
  temp5 = (size_t)jarg5; 
  arg5 = &temp5; 
  result = (UltFace::UltFaceImageInfoRgbFamily *)new UltFace::UltFaceImageInfoRgbFamily((UltFace::ULTFACE_SDK_IMAGE_TYPE const &)*arg1,(void const *)arg2,(size_t const &)*arg3,(size_t const &)*arg4,(size_t const &)*arg5);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_new_UltFaceImageInfoRgbFamily__SWIG_2___(int jarg1, void * jarg2, unsigned int jarg3, unsigned int jarg4) {
  void * jresult ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE *arg1 = 0 ;
  void *arg2 = 0 ;
  size_t *arg3 = 0 ;
  size_t *arg4 = 0 ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE temp1 ;
  size_t temp3 ;
  size_t temp4 ;
  UltFace::UltFaceImageInfoRgbFamily *result = 0 ;
  
  temp1 = (UltFace::ULTFACE_SDK_IMAGE_TYPE)jarg1; 
  arg1 = &temp1; 
  arg2 = jarg2; 
  temp3 = (size_t)jarg3; 
  arg3 = &temp3; 
  temp4 = (size_t)jarg4; 
  arg4 = &temp4; 
  result = (UltFace::UltFaceImageInfoRgbFamily *)new UltFace::UltFaceImageInfoRgbFamily((UltFace::ULTFACE_SDK_IMAGE_TYPE const &)*arg1,(void const *)arg2,(size_t const &)*arg3,(size_t const &)*arg4);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_delete_UltFaceImageInfoRgbFamily___(void * jarg1) {
  UltFace::UltFaceImageInfoRgbFamily *arg1 = 0 ;
  
  arg1 = (UltFace::UltFaceImageInfoRgbFamily *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_new_UltFaceImageInfoYuvFamily__SWIG_0___(int jarg1, void * jarg2, void * jarg3, void * jarg4, unsigned int jarg5, unsigned int jarg6, unsigned int jarg7, unsigned int jarg8, unsigned int jarg9, unsigned int jarg10, int jarg11) {
  void * jresult ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE *arg1 = 0 ;
  void *arg2 = 0 ;
  void *arg3 = 0 ;
  void *arg4 = 0 ;
  size_t *arg5 = 0 ;
  size_t *arg6 = 0 ;
  size_t *arg7 = 0 ;
  size_t *arg8 = 0 ;
  size_t *arg9 = 0 ;
  size_t *arg10 = 0 ;
  int *arg11 = 0 ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE temp1 ;
  size_t temp5 ;
  size_t temp6 ;
  size_t temp7 ;
  size_t temp8 ;
  size_t temp9 ;
  size_t temp10 ;
  int temp11 ;
  UltFace::UltFaceImageInfoYuvFamily *result = 0 ;
  
  temp1 = (UltFace::ULTFACE_SDK_IMAGE_TYPE)jarg1; 
  arg1 = &temp1; 
  arg2 = jarg2; 
  arg3 = jarg3; 
  arg4 = jarg4; 
  temp5 = (size_t)jarg5; 
  arg5 = &temp5; 
  temp6 = (size_t)jarg6; 
  arg6 = &temp6; 
  temp7 = (size_t)jarg7; 
  arg7 = &temp7; 
  temp8 = (size_t)jarg8; 
  arg8 = &temp8; 
  temp9 = (size_t)jarg9; 
  arg9 = &temp9; 
  temp10 = (size_t)jarg10; 
  arg10 = &temp10; 
  temp11 = (int)jarg11; 
  arg11 = &temp11; 
  result = (UltFace::UltFaceImageInfoYuvFamily *)new UltFace::UltFaceImageInfoYuvFamily((UltFace::ULTFACE_SDK_IMAGE_TYPE const &)*arg1,(void const *)arg2,(void const *)arg3,(void const *)arg4,(size_t const &)*arg5,(size_t const &)*arg6,(size_t const &)*arg7,(size_t const &)*arg8,(size_t const &)*arg9,(size_t const &)*arg10,(int const &)*arg11);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_new_UltFaceImageInfoYuvFamily__SWIG_1___(int jarg1, void * jarg2, void * jarg3, void * jarg4, unsigned int jarg5, unsigned int jarg6, unsigned int jarg7, unsigned int jarg8, unsigned int jarg9, unsigned int jarg10) {
  void * jresult ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE *arg1 = 0 ;
  void *arg2 = 0 ;
  void *arg3 = 0 ;
  void *arg4 = 0 ;
  size_t *arg5 = 0 ;
  size_t *arg6 = 0 ;
  size_t *arg7 = 0 ;
  size_t *arg8 = 0 ;
  size_t *arg9 = 0 ;
  size_t *arg10 = 0 ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE temp1 ;
  size_t temp5 ;
  size_t temp6 ;
  size_t temp7 ;
  size_t temp8 ;
  size_t temp9 ;
  size_t temp10 ;
  UltFace::UltFaceImageInfoYuvFamily *result = 0 ;
  
  temp1 = (UltFace::ULTFACE_SDK_IMAGE_TYPE)jarg1; 
  arg1 = &temp1; 
  arg2 = jarg2; 
  arg3 = jarg3; 
  arg4 = jarg4; 
  temp5 = (size_t)jarg5; 
  arg5 = &temp5; 
  temp6 = (size_t)jarg6; 
  arg6 = &temp6; 
  temp7 = (size_t)jarg7; 
  arg7 = &temp7; 
  temp8 = (size_t)jarg8; 
  arg8 = &temp8; 
  temp9 = (size_t)jarg9; 
  arg9 = &temp9; 
  temp10 = (size_t)jarg10; 
  arg10 = &temp10; 
  result = (UltFace::UltFaceImageInfoYuvFamily *)new UltFace::UltFaceImageInfoYuvFamily((UltFace::ULTFACE_SDK_IMAGE_TYPE const &)*arg1,(void const *)arg2,(void const *)arg3,(void const *)arg4,(size_t const &)*arg5,(size_t const &)*arg6,(size_t const &)*arg7,(size_t const &)*arg8,(size_t const &)*arg9,(size_t const &)*arg10);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_new_UltFaceImageInfoYuvFamily__SWIG_2___(int jarg1, void * jarg2, void * jarg3, void * jarg4, unsigned int jarg5, unsigned int jarg6, unsigned int jarg7, unsigned int jarg8, unsigned int jarg9) {
  void * jresult ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE *arg1 = 0 ;
  void *arg2 = 0 ;
  void *arg3 = 0 ;
  void *arg4 = 0 ;
  size_t *arg5 = 0 ;
  size_t *arg6 = 0 ;
  size_t *arg7 = 0 ;
  size_t *arg8 = 0 ;
  size_t *arg9 = 0 ;
  UltFace::ULTFACE_SDK_IMAGE_TYPE temp1 ;
  size_t temp5 ;
  size_t temp6 ;
  size_t temp7 ;
  size_t temp8 ;
  size_t temp9 ;
  UltFace::UltFaceImageInfoYuvFamily *result = 0 ;
  
  temp1 = (UltFace::ULTFACE_SDK_IMAGE_TYPE)jarg1; 
  arg1 = &temp1; 
  arg2 = jarg2; 
  arg3 = jarg3; 
  arg4 = jarg4; 
  temp5 = (size_t)jarg5; 
  arg5 = &temp5; 
  temp6 = (size_t)jarg6; 
  arg6 = &temp6; 
  temp7 = (size_t)jarg7; 
  arg7 = &temp7; 
  temp8 = (size_t)jarg8; 
  arg8 = &temp8; 
  temp9 = (size_t)jarg9; 
  arg9 = &temp9; 
  result = (UltFace::UltFaceImageInfoYuvFamily *)new UltFace::UltFaceImageInfoYuvFamily((UltFace::ULTFACE_SDK_IMAGE_TYPE const &)*arg1,(void const *)arg2,(void const *)arg3,(void const *)arg4,(size_t const &)*arg5,(size_t const &)*arg6,(size_t const &)*arg7,(size_t const &)*arg8,(size_t const &)*arg9);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_delete_UltFaceImageInfoYuvFamily___(void * jarg1) {
  UltFace::UltFaceImageInfoYuvFamily *arg1 = 0 ;
  
  arg1 = (UltFace::UltFaceImageInfoYuvFamily *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_new_UltFaceSdkResult__SWIG_0___() {
  void * jresult ;
  UltFace::UltFaceSdkResult *result = 0 ;
  
  result = (UltFace::UltFaceSdkResult *)new UltFace::UltFaceSdkResult();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_new_UltFaceSdkResult__SWIG_1___(int jarg1, char * jarg2, char * jarg3, unsigned int jarg4) {
  void * jresult ;
  int arg1 ;
  char *arg2 = 0 ;
  char *arg3 = 0 ;
  size_t arg4 ;
  UltFace::UltFaceSdkResult *result = 0 ;
  
  arg1 = (int)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  arg4 = (size_t)jarg4; 
  result = (UltFace::UltFaceSdkResult *)new UltFace::UltFaceSdkResult(arg1,(char const *)arg2,(char const *)arg3,SWIG_STD_MOVE(arg4));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_new_UltFaceSdkResult__SWIG_2___(int jarg1, char * jarg2, char * jarg3) {
  void * jresult ;
  int arg1 ;
  char *arg2 = 0 ;
  char *arg3 = 0 ;
  UltFace::UltFaceSdkResult *result = 0 ;
  
  arg1 = (int)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (UltFace::UltFaceSdkResult *)new UltFace::UltFaceSdkResult(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_new_UltFaceSdkResult__SWIG_3___(void * jarg1) {
  void * jresult ;
  UltFace::UltFaceSdkResult *arg1 = 0 ;
  UltFace::UltFaceSdkResult *result = 0 ;
  
  arg1 = (UltFace::UltFaceSdkResult *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "UltFace::UltFaceSdkResult const & is null", 0);
    return 0;
  } 
  result = (UltFace::UltFaceSdkResult *)new UltFace::UltFaceSdkResult((UltFace::UltFaceSdkResult const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_delete_UltFaceSdkResult___(void * jarg1) {
  UltFace::UltFaceSdkResult *arg1 = 0 ;
  
  arg1 = (UltFace::UltFaceSdkResult *)jarg1; 
  delete arg1;
}


SWIGEXPORT int SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkResult_code___(void * jarg1) {
  int jresult ;
  UltFace::UltFaceSdkResult *arg1 = 0 ;
  int result;
  
  arg1 = (UltFace::UltFaceSdkResult *)jarg1; 
  result = (int)((UltFace::UltFaceSdkResult const *)arg1)->code();
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkResult_phrase___(void * jarg1) {
  char * jresult ;
  UltFace::UltFaceSdkResult *arg1 = 0 ;
  char *result = 0 ;
  
  arg1 = (UltFace::UltFaceSdkResult *)jarg1; 
  result = (char *)((UltFace::UltFaceSdkResult const *)arg1)->phrase();
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkResult_json___(void * jarg1) {
  char * jresult ;
  UltFace::UltFaceSdkResult *arg1 = 0 ;
  char *result = 0 ;
  
  arg1 = (UltFace::UltFaceSdkResult *)jarg1; 
  result = (char *)((UltFace::UltFaceSdkResult const *)arg1)->json();
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkResult_numFaces___(void * jarg1) {
  unsigned int jresult ;
  UltFace::UltFaceSdkResult *arg1 = 0 ;
  size_t result;
  
  arg1 = (UltFace::UltFaceSdkResult *)jarg1; 
  result = ((UltFace::UltFaceSdkResult const *)arg1)->numFaces();
  jresult = (unsigned int)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkResult_isOK___(void * jarg1) {
  unsigned int jresult ;
  UltFace::UltFaceSdkResult *arg1 = 0 ;
  bool result;
  
  arg1 = (UltFace::UltFaceSdkResult *)jarg1; 
  result = (bool)((UltFace::UltFaceSdkResult const *)arg1)->isOK();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_delete_UltFaceSdkParallelDeliveryCallback___(void * jarg1) {
  UltFace::UltFaceSdkParallelDeliveryCallback *arg1 = 0 ;
  
  arg1 = (UltFace::UltFaceSdkParallelDeliveryCallback *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkParallelDeliveryCallback_onNewResult___(void * jarg1, void * jarg2) {
  UltFace::UltFaceSdkParallelDeliveryCallback *arg1 = 0 ;
  UltFace::UltFaceSdkResult *arg2 = 0 ;
  
  arg1 = (UltFace::UltFaceSdkParallelDeliveryCallback *)jarg1; 
  arg2 = (UltFace::UltFaceSdkResult *)jarg2; 
  ((UltFace::UltFaceSdkParallelDeliveryCallback const *)arg1)->onNewResult((UltFace::UltFaceSdkResult const *)arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkEngine_init__SWIG_0___(char * jarg1, void * jarg2) {
  void * jresult ;
  char *arg1 = 0 ;
  UltFace::UltFaceSdkParallelDeliveryCallback *arg2 = 0 ;
  UltFace::UltFaceSdkResult result;
  
  arg1 = (char *)jarg1; 
  arg2 = (UltFace::UltFaceSdkParallelDeliveryCallback *)jarg2; 
  result = UltFace::UltFaceSdkEngine::init((char const *)arg1,(UltFace::UltFaceSdkParallelDeliveryCallback const *)arg2);
  jresult = new UltFace::UltFaceSdkResult(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkEngine_init__SWIG_1___(char * jarg1) {
  void * jresult ;
  char *arg1 = 0 ;
  UltFace::UltFaceSdkResult result;
  
  arg1 = (char *)jarg1; 
  result = UltFace::UltFaceSdkEngine::init((char const *)arg1);
  jresult = new UltFace::UltFaceSdkResult(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkEngine_deInit___() {
  void * jresult ;
  UltFace::UltFaceSdkResult result;
  
  result = UltFace::UltFaceSdkEngine::deInit();
  jresult = new UltFace::UltFaceSdkResult(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkEngine_process_liveness___(void * jarg1) {
  void * jresult ;
  UltFace::UltFaceImageInfo *arg1 = 0 ;
  UltFace::UltFaceSdkResult result;
  
  arg1 = (UltFace::UltFaceImageInfo *)jarg1; 
  result = UltFace::UltFaceSdkEngine::process_liveness((UltFace::UltFaceImageInfo const *)arg1);
  jresult = new UltFace::UltFaceSdkResult(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkEngine_process_inject__SWIG_0___(void * jarg1, void * jarg2, char * jarg3) {
  void * jresult ;
  UltFace::UltFaceImageInfo *arg1 = 0 ;
  UltFace::UltFaceImageInfo *arg2 = 0 ;
  char *arg3 = 0 ;
  UltFace::UltFaceSdkResult result;
  
  arg1 = (UltFace::UltFaceImageInfo *)jarg1; 
  arg2 = (UltFace::UltFaceImageInfo *)jarg2; 
  arg3 = (char *)jarg3; 
  result = UltFace::UltFaceSdkEngine::process_inject((UltFace::UltFaceImageInfo const *)arg1,(UltFace::UltFaceImageInfo const *)arg2,(char const *)arg3);
  jresult = new UltFace::UltFaceSdkResult(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkEngine_process_inject__SWIG_1___(void * jarg1, void * jarg2) {
  void * jresult ;
  UltFace::UltFaceImageInfo *arg1 = 0 ;
  UltFace::UltFaceImageInfo *arg2 = 0 ;
  UltFace::UltFaceSdkResult result;
  
  arg1 = (UltFace::UltFaceImageInfo *)jarg1; 
  arg2 = (UltFace::UltFaceImageInfo *)jarg2; 
  result = UltFace::UltFaceSdkEngine::process_inject((UltFace::UltFaceImageInfo const *)arg1,(UltFace::UltFaceImageInfo const *)arg2);
  jresult = new UltFace::UltFaceSdkResult(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkEngine_process_recognition___(void * jarg1) {
  void * jresult ;
  UltFace::UltFaceImageInfo *arg1 = 0 ;
  UltFace::UltFaceSdkResult result;
  
  arg1 = (UltFace::UltFaceImageInfo *)jarg1; 
  result = UltFace::UltFaceSdkEngine::process_recognition((UltFace::UltFaceImageInfo const *)arg1);
  jresult = new UltFace::UltFaceSdkResult(result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkEngine_exifOrientation___(void * jarg1, unsigned int jarg2) {
  int jresult ;
  void *arg1 = 0 ;
  size_t arg2 ;
  int result;
  
  arg1 = jarg1; 
  arg2 = (size_t)jarg2; 
  result = (int)UltFace::UltFaceSdkEngine::exifOrientation((void const *)arg1,SWIG_STD_MOVE(arg2));
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkEngine_requestRuntimeLicenseKey__SWIG_0___(unsigned int jarg1) {
  void * jresult ;
  bool *arg1 = 0 ;
  bool temp1 ;
  UltFace::UltFaceSdkResult result;
  
  temp1 = jarg1 ? true : false; 
  arg1 = &temp1; 
  result = UltFace::UltFaceSdkEngine::requestRuntimeLicenseKey((bool const &)*arg1);
  jresult = new UltFace::UltFaceSdkResult(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceSdkEngine_requestRuntimeLicenseKey__SWIG_1___() {
  void * jresult ;
  UltFace::UltFaceSdkResult result;
  
  result = UltFace::UltFaceSdkEngine::requestRuntimeLicenseKey();
  jresult = new UltFace::UltFaceSdkResult(result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_delete_UltFaceSdkEngine___(void * jarg1) {
  UltFace::UltFaceSdkEngine *arg1 = 0 ;
  
  arg1 = (UltFace::UltFaceSdkEngine *)jarg1; 
  delete arg1;
}


SWIGEXPORT UltFace::UltFaceImageInfo * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceImageInfoCompressed_SWIGUpcast___(UltFace::UltFaceImageInfoCompressed *jarg1) {
    return (UltFace::UltFaceImageInfo *)jarg1;
}

SWIGEXPORT UltFace::UltFaceImageInfo * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceImageInfoUncompressed_SWIGUpcast___(UltFace::UltFaceImageInfoUncompressed *jarg1) {
    return (UltFace::UltFaceImageInfo *)jarg1;
}

SWIGEXPORT UltFace::UltFaceImageInfoUncompressed * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceImageInfoRgbFamily_SWIGUpcast___(UltFace::UltFaceImageInfoRgbFamily *jarg1) {
    return (UltFace::UltFaceImageInfoUncompressed *)jarg1;
}

SWIGEXPORT UltFace::UltFaceImageInfoUncompressed * SWIGSTDCALL CSharp_orgfdoubangofUltFacefSdk_UltFaceImageInfoYuvFamily_SWIGUpcast___(UltFace::UltFaceImageInfoYuvFamily *jarg1) {
    return (UltFace::UltFaceImageInfoUncompressed *)jarg1;
}

#ifdef __cplusplus
}
#endif

