//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.doubango.UltFace.Sdk {

public class ultimateFaceSDK {
  public static readonly int ULTFACE_SDK_VERSION_MAJOR = ultimateFaceSDKPINVOKE.ULTFACE_SDK_VERSION_MAJOR_get();
  public static readonly int ULTFACE_SDK_VERSION_MINOR = ultimateFaceSDKPINVOKE.ULTFACE_SDK_VERSION_MINOR_get();
  public static readonly int ULTFACE_SDK_VERSION_MICRO = ultimateFaceSDKPINVOKE.ULTFACE_SDK_VERSION_MICRO_get();
}

}
