# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

package ultimateFaceSDK;
use base qw(Exporter);
use base qw(DynaLoader);
package ultimateFaceSDKc;
bootstrap ultimateFaceSDK;
package ultimateFaceSDK;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package ultimateFaceSDK;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package ultimateFaceSDK;


############# Class : ultimateFaceSDK::UltFaceImageInfo ##############

package ultimateFaceSDK::UltFaceImageInfo;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( ultimateFaceSDK );
%OWNER = ();
%ITERATORS = ();
*Compressed = *ultimateFaceSDKc::UltFaceImageInfo_Compressed;
*Uncompressed = *ultimateFaceSDKc::UltFaceImageInfo_Uncompressed;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        ultimateFaceSDKc::delete_UltFaceImageInfo($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : ultimateFaceSDK::UltFaceImageInfoCompressed ##############

package ultimateFaceSDK::UltFaceImageInfoCompressed;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( ultimateFaceSDK::UltFaceImageInfo ultimateFaceSDK );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = ultimateFaceSDKc::new_UltFaceImageInfoCompressed(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        ultimateFaceSDKc::delete_UltFaceImageInfoCompressed($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : ultimateFaceSDK::UltFaceImageInfoUncompressed ##############

package ultimateFaceSDK::UltFaceImageInfoUncompressed;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( ultimateFaceSDK::UltFaceImageInfo ultimateFaceSDK );
%OWNER = ();
%ITERATORS = ();
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        ultimateFaceSDKc::delete_UltFaceImageInfoUncompressed($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : ultimateFaceSDK::UltFaceImageInfoRgbFamily ##############

package ultimateFaceSDK::UltFaceImageInfoRgbFamily;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( ultimateFaceSDK::UltFaceImageInfoUncompressed ultimateFaceSDK );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = ultimateFaceSDKc::new_UltFaceImageInfoRgbFamily(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        ultimateFaceSDKc::delete_UltFaceImageInfoRgbFamily($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : ultimateFaceSDK::UltFaceImageInfoYuvFamily ##############

package ultimateFaceSDK::UltFaceImageInfoYuvFamily;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( ultimateFaceSDK::UltFaceImageInfoUncompressed ultimateFaceSDK );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = ultimateFaceSDKc::new_UltFaceImageInfoYuvFamily(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        ultimateFaceSDKc::delete_UltFaceImageInfoYuvFamily($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : ultimateFaceSDK::UltFaceSdkResult ##############

package ultimateFaceSDK::UltFaceSdkResult;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( ultimateFaceSDK );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = ultimateFaceSDKc::new_UltFaceSdkResult(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        ultimateFaceSDKc::delete_UltFaceSdkResult($self);
        delete $OWNER{$self};
    }
}

*code = *ultimateFaceSDKc::UltFaceSdkResult_code;
*phrase = *ultimateFaceSDKc::UltFaceSdkResult_phrase;
*json = *ultimateFaceSDKc::UltFaceSdkResult_json;
*numFaces = *ultimateFaceSDKc::UltFaceSdkResult_numFaces;
*isOK = *ultimateFaceSDKc::UltFaceSdkResult_isOK;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : ultimateFaceSDK::UltFaceSdkParallelDeliveryCallback ##############

package ultimateFaceSDK::UltFaceSdkParallelDeliveryCallback;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( ultimateFaceSDK );
%OWNER = ();
%ITERATORS = ();
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        ultimateFaceSDKc::delete_UltFaceSdkParallelDeliveryCallback($self);
        delete $OWNER{$self};
    }
}

*onNewResult = *ultimateFaceSDKc::UltFaceSdkParallelDeliveryCallback_onNewResult;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : ultimateFaceSDK::UltFaceSdkEngine ##############

package ultimateFaceSDK::UltFaceSdkEngine;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( ultimateFaceSDK );
%OWNER = ();
%ITERATORS = ();
*init = *ultimateFaceSDKc::UltFaceSdkEngine_init;
*deInit = *ultimateFaceSDKc::UltFaceSdkEngine_deInit;
*process_liveness = *ultimateFaceSDKc::UltFaceSdkEngine_process_liveness;
*process_inject = *ultimateFaceSDKc::UltFaceSdkEngine_process_inject;
*process_recognition = *ultimateFaceSDKc::UltFaceSdkEngine_process_recognition;
*exifOrientation = *ultimateFaceSDKc::UltFaceSdkEngine_exifOrientation;
*requestRuntimeLicenseKey = *ultimateFaceSDKc::UltFaceSdkEngine_requestRuntimeLicenseKey;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        ultimateFaceSDKc::delete_UltFaceSdkEngine($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package ultimateFaceSDK;

*ULTFACE_SDK_VERSION_MAJOR = *ultimateFaceSDKc::ULTFACE_SDK_VERSION_MAJOR;
*ULTFACE_SDK_VERSION_MINOR = *ultimateFaceSDKc::ULTFACE_SDK_VERSION_MINOR;
*ULTFACE_SDK_VERSION_MICRO = *ultimateFaceSDKc::ULTFACE_SDK_VERSION_MICRO;
*ULTFACE_SDK_IMAGE_TYPE_RGB24 = *ultimateFaceSDKc::ULTFACE_SDK_IMAGE_TYPE_RGB24;
*ULTFACE_SDK_IMAGE_TYPE_RGBA32 = *ultimateFaceSDKc::ULTFACE_SDK_IMAGE_TYPE_RGBA32;
*ULTFACE_SDK_IMAGE_TYPE_BGRA32 = *ultimateFaceSDKc::ULTFACE_SDK_IMAGE_TYPE_BGRA32;
*ULTFACE_SDK_IMAGE_TYPE_BGR24 = *ultimateFaceSDKc::ULTFACE_SDK_IMAGE_TYPE_BGR24;
*ULTFACE_SDK_IMAGE_TYPE_NV12 = *ultimateFaceSDKc::ULTFACE_SDK_IMAGE_TYPE_NV12;
*ULTFACE_SDK_IMAGE_TYPE_NV21 = *ultimateFaceSDKc::ULTFACE_SDK_IMAGE_TYPE_NV21;
*ULTFACE_SDK_IMAGE_TYPE_YUV420P = *ultimateFaceSDKc::ULTFACE_SDK_IMAGE_TYPE_YUV420P;
*ULTFACE_SDK_IMAGE_TYPE_YVU420P = *ultimateFaceSDKc::ULTFACE_SDK_IMAGE_TYPE_YVU420P;
*ULTFACE_SDK_IMAGE_TYPE_YUV422P = *ultimateFaceSDKc::ULTFACE_SDK_IMAGE_TYPE_YUV422P;
*ULTFACE_SDK_IMAGE_TYPE_YUV444P = *ultimateFaceSDKc::ULTFACE_SDK_IMAGE_TYPE_YUV444P;
*ULTFACE_SDK_IMAGE_TYPE_Y = *ultimateFaceSDKc::ULTFACE_SDK_IMAGE_TYPE_Y;
1;
